# Server
markdown:         rdiscount
pygments:         true
relative_permalinks: true
destination:      ./_gh_pages
exclude:          [".idea", ".editorconfig", ".gitignore", "bower.json", "composer.json", "CONTRIBUTING.md", "CNAME", "LICENSE",
                  "Gruntfile.js", "package.json", "node_modules", "README.md", "dist", "less", "metro",
                  "tests", "raw-files.js", "validation-report.json", "validation-status.json"]
host:             0.0.0.0
port:             4000
baseurl:          "/metro-ui-jekyll/"

# Custom vars
current_version:  2.0.31

ghauthor:         "A-G-F"
ghproject:        "metro-ui-jekyll"
ghname:           "Metro UI 4 Jekyll"
locale:           "en"
ga-acc:           "UA-2732939-9" # your Google Analytics tracking No., e.g.  UA-123456789-1

defaults:
  -
    scope:
      path:       ""
    values:
      layout:     "standard"
